import type { Metadata } from "next";
import "./globals.css";
import LoaderLayout from "../components/LoaderLayout";

export const metadata: Metadata = {
  title: "Pokemon Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <LoaderLayout>{children}</LoaderLayout>
      </body>
    </html>
  );
}
